version: '3'
services:
    bot:
        build: ./
        ports:
            - 8080:8080
        depends_on:
            - db
    db:
        image: postgres
        expose:
            - 5432
        environment:
            POSTGRES_USER: frobo
            POSTGRES_PASSWORD: frobo
        volumes:
            - /var/lib/postgresql/data